Added ability to automatically choose contrasting color for titleBar.…
oreporan/color-tabs-vscode pull request #16
Opened 2019-04-28 12:18 UTC by fyrebase

This PR changes the title text color so it contrasts with the title background color

2019-04-28 14:11 UTC, oreporan commented
I like it :)

2019-04-28 14:15 UTC, oreporan commented on src/changeColors.ts
> +const invertHex = (hex) => {
`const invertHex = hex => hex && hex.replace('#', '0x') > 0xffffff / 2 ? '#000000' : '#ffffff';`

2019-04-29 11:54 UTC, oreporan approved these changes

2019-04-29 11:55 UTC, fyrebase commented
Added automatic contrast to activity bar and status bar as well ;)

2019-04-29 11:57 UTC, oreporan requested changes

2019-04-29 11:57 UTC, oreporan commented on src/changeColors.ts
> +    const titleBarForegroundColor = titleBackground ? invertHex(color) : undefined;
just for sake of redundant function calls, can you set invertHex at the top

2019-04-29 12:03 UTC, merged