Add option to color tab background
oreporan/color-tabs-vscode pull request #61
Opened 2022-05-11 16:17 UTC by nerijusdu

Hi 👋, 
I love this extension, but sometimes it's hard to notice the tab border color (especially when there's a horizontal scrollbar).

This PR introduces an additional option to set the background color of the active tab so that it would be more visible.

2022-05-11 20:00 UTC, oreporan requested changes

2022-05-11 20:00 UTC, oreporan commented on package.json
> +          "default": true,
Set default to false

2022-05-11 20:01 UTC, oreporan commented
Hey :) thanks
Have you tried setting all the other configs to true? Such as activityBar and title?

2022-05-13 17:34 UTC, nerijusdu commented
The activity bar and title bar flashing with different colors look a little too intrusive for me

2022-05-15 07:59 UTC, oreporan approved these changes

2022-05-15 07:59 UTC, merged